### PR TITLE
Implement new features

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by shrayasr** [comment]
Wow. This is totally unexpected and awesome. Will review soon! Thank you :tada: :)

**Comment by astronomersiva** [comment]
Sure man! I am back in action 😎 

This MR is literally from the stone-age. November, 2015 😆

**Comment by astronomersiva** [comment]
@shrayasr  🔔 😆

**Comment by shrayasr** [comment]
Haha wow. I had totally forgotten about this! Thanks man :)

**Pull request merged**
